# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: arXiv-daily-ai-enhanced

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync

      - name: Crawl arXiv papers
        id: crawl_step
        run: |
          source .venv/bin/activate
          today=$(date -u "+%Y-%m-%d")
          echo "开始爬取 $today 的arXiv论文..."

          # 检查今日文件是否已存在，如存在则删除
          if [ -f "data/${today}.jsonl" ]; then
              echo "发现今日文件已存在，正在删除重新生成..."
              rm "data/${today}.jsonl"
              echo "已删除现有文件：data/${today}.jsonl"
          else
              echo "今日文件不存在，准备新建..."
          fi

          cd daily_arxiv
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          export OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }}
          export LANGUAGE="${{ vars.LANGUAGE }}"
          export CATEGORIES="${{ vars.CATEGORIES }}"
          export MODEL_NAME="${{ vars.MODEL_NAME }}"

          # 使用Scrapy爬取
          # Use Scrapy to crawl
          scrapy crawl arxiv -o ../data/${today}.jsonl

          # 检查爬取是否成功
          if [ ! -f "../data/${today}.jsonl" ]; then
              echo "爬取失败，未生成数据文件"
              exit 1
          fi

          echo "crawl_date=$today" >> $GITHUB_OUTPUT
          echo "爬取完成"

      - name: Check for duplicates
        id: dedup_check
        run: |
          source .venv/bin/activate
          echo "执行去重检查..."

          cd daily_arxiv
          # 执行去重检查脚本
          set +e  # 暂时允许命令失败
          python daily_arxiv/check_stats.py

          # 获取退出码
          dedup_exit_code=$?
          set -e  # 恢复严格模式

          echo "去重检查退出码: $dedup_exit_code"
          echo "dedup_exit_code=$dedup_exit_code" >> $GITHUB_OUTPUT

          case $dedup_exit_code in
              0)
                  echo "has_new_content=true" >> $GITHUB_OUTPUT
                  ;;
              1)
                  echo "has_new_content=false" >> $GITHUB_OUTPUT
                  echo "skip_reason=no_new_content" >> $GITHUB_OUTPUT
                  ;;
              2)
                  echo "has_new_content=false" >> $GITHUB_OUTPUT
                  echo "skip_reason=processing_error" >> $GITHUB_OUTPUT
                  exit 1
                  ;;
              *)
                  echo "未知退出码，停止工作流"
                  echo "has_new_content=false" >> $GITHUB_OUTPUT
                  echo "skip_reason=unknown_error" >> $GITHUB_OUTPUT
                  exit 1
                  ;;
          esac

      - name: AI Enhancement Processing
        if: steps.dedup_check.outputs.has_new_content == 'true'
        run: |
          source .venv/bin/activate
          today=${{ steps.crawl_step.outputs.crawl_date }}
          echo "开始AI增强处理..."

          cd ai
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          export OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }}
          export LANGUAGE="${{ vars.LANGUAGE }}"
          export MODEL_NAME="${{ vars.MODEL_NAME }}"

          python enhance.py --data ../data/${today}.jsonl

          # 检查AI处理是否成功
          if [ $? -ne 0 ]; then
              echo "AI处理失败"
              exit 1
          fi
          echo "AI增强处理完成"

      - name: Convert to Markdown
        if: steps.dedup_check.outputs.has_new_content == 'true'
        run: |
          source .venv/bin/activate
          today=${{ steps.crawl_step.outputs.crawl_date }}
          echo "转换为Markdown格式..."

          # 设置环境变量
          export LANGUAGE="${{ vars.LANGUAGE }}"

          cd to_md

          # 使用AI增强文件进行转换
          AI_FILE="../data/${today}_AI_enhanced_${LANGUAGE}.jsonl"

          if [ -f "$AI_FILE" ]; then
              echo "使用AI增强文件进行转换..."
              python convert.py --data "$AI_FILE"
          else
              echo "错误：未找到AI增强文件"
              echo "AI文件: $AI_FILE"
              exit 1
          fi

          # 检查转换是否成功
          if [ $? -ne 0 ]; then
              echo "Markdown转换失败"
              exit 1
          fi
          echo "Markdown转换完成"

      - name: Update file list
        if: steps.dedup_check.outputs.has_new_content == 'true'
        run: |
          echo "更新文件列表..."
          ls data/*.jsonl | sed 's|data/||' > assets/file-list.txt
          echo "文件列表更新完成"

      - name: Summary
        run: |
          if [ "${{ steps.dedup_check.outputs.has_new_content }}" = "true" ]; then
            echo "工作流完成：去重发现新内容并成功处理"
          else
            case "${{ steps.dedup_check.outputs.skip_reason }}" in
              "no_new_content")
                echo "ℹ工作流完成：去重后无新内容 deduplication"
                ;;
              "processing_error")
                echo "工作流完成：去重处理出错"
                ;;
              "unknown_error")
                echo "工作流完成：未知错误"
                ;;
              *)
                echo "工作流完成：未知原因跳过处理"
                ;;
            esac
          fi

      - name: Commit changes
        if: steps.dedup_check.outputs.has_new_content == 'true'
        run: |
          git config --global user.email "${{ vars.EMAIL }}"
          git config --global user.name "${{ vars.NAME }}"
          git add .
          # 检查是否有变更需要提交
          if git diff --staged --quiet; then
            echo "没有变更需要提交"
            exit 0
          fi
          git commit -m "update: $(date -u '+%Y-%m-%d') arXiv papers"
          echo "变更已提交"

      - name: Pull latest changes and push
        if: steps.dedup_check.outputs.has_new_content == 'true'
        run: |
          # 设置Git配置以处理自动合并
          git config pull.rebase true
          git config rebase.autoStash true

          # 尝试推送，如果失败则拉取并重试
          for i in {1..3}; do
            echo "推送尝试 $i"
            if git push origin main; then
              echo "推送成功"
              break
            else
              echo "推送失败，拉取最新变更..."
              git pull origin main --no-edit || true
              if [ $i -eq 3 ]; then
                echo "3次尝试后推送失败"
                exit 1
              fi
            fi
          done
